apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: app-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: lb-deploy
spec:
  selector:
    app: app-nginx
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80

