apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mono-app
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./dec/15-deploy
    repoURL: 'https://github.com/janardhanReddy-B/gke'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true