apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-private
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-private
  template:
    metadata:
      labels:
        app: nginx-private
    spec:
       containers:
          - name: nginx
            image: nginx
