apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-1
  labels:
    app: rs-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rs-app
  template:
    metadata:
      name: rs-1
      labels:
        app: rs-1
    spec:
      containers:
      - name: rs-app
        image: nginx
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: lb-for-rs
spec:
  selector:
    app: rs-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
